version: "3.9"
services:
  peerbanhelper:
    image: "ghostchu/peerbanhelper:<最新版本号>"
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ./:/app/data
    ports:
      - "9898:9898"
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC