version: "3.9"
services:
  peerbanhelper:
    image: registry.cn-hangzhou.aliyuncs.com/ghostchu/peerbanhelper:latest
    restart: always
    container_name: "peerbanhelper"
    volumes:
      - /var/packages/peerbanhelper/shares/peerbanhelper:/app/data
    ports:
      - "9898:9898"
    environment:
      - PBH_USER_LOCALE=zh-CN