name: build Installers

on:
  workflow_call:
    secrets:
      INSTALL4J_LICENSE:
        required: true
jobs:
  Build_Installers:
    needs: WebUI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        uses: jactions/maven-version@v1.2.0
      - uses: actions/download-artifact@v4
        with:
          name: maven-dist
          path: target/
      - uses: luangong/setup-install4j@v1
        name: Setup Install4j
        with:
          version: 10.0.8
          license: ${{ secrets.INSTALL4J_LICENSE }}
      - name: Make installers
        run: /opt/install4j/install4jc -L ${{ secrets.INSTALL4J_LICENSE }} -r ${{ steps.get-version.outputs.version }} -d target/media -D jarPath=target/PeerBanHelper.jar install4j/project.install4j
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer-dist
          path: |
            target/media/*.exe
            target/media/*.dmg
            target/media/*.rpm
            target/media/*.deb
            target/media/*.sh
        id: project