name: build Installers

on:
  workflow_call:
    secrets:
      INSTALL4J_LICENSE:
        required: true
jobs:
  Build_Installers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        uses: andreacomo/maven-gav-extractor@v2
      - uses: actions/download-artifact@v4
        with:
          name: maven-dist
          path: target/
      - uses: luangong/setup-install4j@v1
        name: Setup Install4j
        with:
          version: 10.0.8
          license: ${{ secrets.INSTALL4J_LICENSE }}
      - name: Make installers
        run: |
          ls /opt/install4j/
          /opt/install4j/bin/install4jc -L ${{ secrets.INSTALL4J_LICENSE }} -r ${{ steps.extract.outputs.version }} -d target/media -D jarPath=target/PeerBanHelper.jar install4j/project.install4j
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer-dist
          path: |
            target/media/PeerBanHelper_*
        id: project