# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on:
  push:
  workflow_dispatch:
jobs:
  CI:
    uses: ./.github/workflows/build_maven.yml
    with:
      install4j_license: ${{ secrets.INSTALL4J_LICENSE }}
  Build_Docker:
    needs: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: maven-dist
        path: target
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set Up Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ghostchu/peerbanhelper-snapshot
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,ci-jvm-universal
          type=raw,ci
          type=sha
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        file: ./Dockerfile-CI
        push: true
        platforms: |
          linux/amd64
          linux/arm64/v8
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}-jvm-universal
        cache-from: type=gha
        cache-to: type=gha,mode=max
  Build_SPK:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        uses: jactions/maven-version@v1.2.0
      - uses: actions/download-artifact@v4
        with:
          name: maven-dist
          path: target/
      - name: Set Up Synology SDK
        run: |
          sudo mkdir -p /tmp/pbh-packages
          sudo cp -av synopkg/* /tmp/pbh-packages
          sudo apt-get install git
          sudo mkdir -p /toolkit
          sudo cd /toolkit
          sudo git clone https://github.com/SynologyOpenSource/pkgscripts-ng
          sudo apt-get install cifs-utils python3 python3-pip
          sudo cd /toolkit/pkgscripts-ng/
          sudo git checkout DSM7.2
          sudo ./EnvDeploy -v 7.2 -p apollolake
          sudo mkdir -p /toolkit/source
      - name: Prepare for package build
        run: |
          sudo cp -av /tmp/pbh-packages/* /toolkit/source/
          sudo sed -i "s/@IMAGE@/ghostchu\/peerbanhelper-snapshot:sha-${{ github.sha }}/g" /toolkit/source/PeerBanHelperPackage/target/app/docker-compose.yaml
          sudo cat /toolkit/source/PeerBanHelperPackage/target/app/docker-compose.yaml
          sudo sed -i "s/@PBH_VERSION@/${{ steps.get-version.outputs.version }}/g" /toolkit/source/PeerBanHelperPackage/INFO.sh
          sudo cat /toolkit/source/PeerBanHelperPackage/INFO.sh
      - name: Compile Synology SPK
        run: |
          sudo /toolkit/pkgscripts-ng/PkgCreate.py -v 7.2 -p apollolake -c PeerBanHelperPackage
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SynologySPK-${{ github.sha }}
          path: |
            /toolkit/build_env/ds.apollolake-7.2/image/packages/*.spk