# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Release

on:
  workflow_dispatch:
  release:
    types:
      - published
jobs:
  Build_Executable:
    secrets: inherit
    uses: ./.github/workflows/build_maven.yml
  Upload_Artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: maven-dist
          path: target
      - uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["target/PeerBanHelper.jar", "target/media/PeerBanHelper_*"]'
        id: project
  Build_Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghostchu/peerbanhelper
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,latest-jvm-universal
            type=raw,latest
            type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}-jvm-universal
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_HASH=${{ github.sha }}
      # ---------------- ALIYUN ACR --------------------
      - name: Log in to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: "registry.cn-hangzhou.aliyuncs.com"
          username: ${{ secrets.ALIYUN_ACR_USERNAME }}
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
      - name: Extract metadata (tags, labels) for Aliyun ACR
        id: meta-acr
        uses: docker/metadata-action@v5.5.1
        with:
          images: registry.cn-hangzhou.aliyuncs.com/ghostchu/peerbanhelper
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,latest-jvm-universal
            type=raw,latest
            type=sha
      - name: Build and push Aliyun ACR
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
          tags: ${{ steps.meta-acr.outputs.tags }}
          labels: ${{ steps.meta-acr.outputs.labels }}-jvm-universal
          cache-from: type=gha
          cache-to: type=gha,mode=max
  Build_SPK:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        uses: jactions/maven-version@v1.2.0
      - uses: actions/download-artifact@v4
        with:
          name: maven-dist
          path: target/
      - name: Run build script
        run: sudo bash synopkg/build-script.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SynologySPK-${{ github.sha }}
          path: |
            /toolkit/build_env/ds.apollolake-7.2/image/packages/*.spk