name: Make torrent

on:
  workflow_call:
    inputs:
      path:
        description: 'The path of the file to be made torrent'
        required: true
        type: string
      dest:
        description: 'The path of the torrent file will put at, do not end with /'
        required: true
        type: string
      torrentfile:
        description: 'The name of the torrent file'
        required: true
        type: string
jobs:
  mktorrent:
    runs-on: ubuntu-latest
    steps:
      # prepare mktorrent util
      - name: Install mktorrent
        run: sudo apt-get install -y mktorrent
      # make torrent
      - name: Make torrent
        run: mktorrent -a udp://tracker.opentrackr.org:1337/announce -a udp://tracker.publicbt.com:80/announce -a udp://tracker.openbittorrent.com:80/announce -a https://sparkle.ghostchu-services.top/annonce -a udp://opentracker.io:6969/announce -a wss://tracker.openwebtorrent.com:443/announce -c "PeerBanHelper/${{ github.ref }} (${{ github.sha }}) on ${{ github.repository }}. Published by ${{ github.repository_owner }}." -w https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/ -o ${{ inputs.dest }}/${{ inputs.torrentfile }} ${{ inputs.path }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: torrent-dist
          path: |
            ${{ inputs.dest }}/${{ inputs.torrentfile }}
        id: project